CREATE TABLE [dbo].[LKUP_SQLServerVersions]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(30) NULL, 
    [CodeName] VARCHAR(20) NULL, 
    [RTM] VARCHAR(20) NULL, 
    [SP1] VARCHAR(20) NULL,
	[SP2] VARCHAR(20) NULL,
	[SP3] VARCHAR(20) NULL,
    [SP4] VARCHAR(20) NULL
)
