//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamDiagnostics {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamDiagnostics.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names should be all uppercase..
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name &apos;{0}&apos; contains lowercase letters.
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type name contains lowercase letters.
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove catch block.
        /// </summary>
        internal static string EmptyCatchClause00CodeFixMessage {
            get {
                return ResourceManager.GetString("EmptyCatchClause00CodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove catch block and add comment.
        /// </summary>
        internal static string EmptyCatchClause01CodeFixMessage {
            get {
                return ResourceManager.GetString("EmptyCatchClause01CodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove catch block and braces.
        /// </summary>
        internal static string EmptyCatchClause02CodeFixMessage {
            get {
                return ResourceManager.GetString("EmptyCatchClause02CodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch exception and rethrow.
        /// </summary>
        internal static string EmptyCatchClause03CodeFixMessage {
            get {
                return ResourceManager.GetString("EmptyCatchClause03CodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch clause should not be empty.
        /// </summary>
        internal static string EmptyCatchClauseDescription {
            get {
                return ResourceManager.GetString("EmptyCatchClauseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch clause is empty.
        /// </summary>
        internal static string EmptyCatchClauseMessageFormat {
            get {
                return ResourceManager.GetString("EmptyCatchClauseMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch clause is empty.
        /// </summary>
        internal static string EmptyCatchClauseTitle {
            get {
                return ResourceManager.GetString("EmptyCatchClauseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make variables {0} constants.
        /// </summary>
        internal static string LocalVariableCouldBeConstantCodeFixMessage {
            get {
                return ResourceManager.GetString("LocalVariableCouldBeConstantCodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable could be constant.
        /// </summary>
        internal static string LocalVariableCouldBeConstantDescription {
            get {
                return ResourceManager.GetString("LocalVariableCouldBeConstantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable {0} could be constant.
        /// </summary>
        internal static string LocalVariableCouldBeConstantMessageFormat {
            get {
                return ResourceManager.GetString("LocalVariableCouldBeConstantMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable could be constant.
        /// </summary>
        internal static string LocalVariableCouldBeConstantTitle {
            get {
                return ResourceManager.GetString("LocalVariableCouldBeConstantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seal attribute classes.
        /// </summary>
        internal static string NonSealedAttributeCodeFixMessage {
            get {
                return ResourceManager.GetString("NonSealedAttributeCodeFixMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-sealed attribute classes can cause performance and security issues.
        /// </summary>
        internal static string NonSealedAttributeDescription {
            get {
                return ResourceManager.GetString("NonSealedAttributeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute class {0} should be sealed.
        /// </summary>
        internal static string NonSealedAttributeMessageFormat {
            get {
                return ResourceManager.GetString("NonSealedAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute classes should be sealed.
        /// </summary>
        internal static string NonSealedAttributeTitle {
            get {
                return ResourceManager.GetString("NonSealedAttributeTitle", resourceCulture);
            }
        }
    }
}
