CREATE TABLE [dbo].[Instances]
(
	[ID] UNIQUEIDENTIFIER NOT NULL DEFAULT (newid()), 
    [Server_ID] UNIQUEIDENTIFIER NULL, 
    [SnapShotDate] DATETIME NULL, 
    [SnapShotError] VARCHAR(256) NULL, 
	[Name_Instance] VARCHAR(256) NOT NULL,
	[BrowserStartMode] VARCHAR(50) NULL,
    [Collation] VARCHAR(50) NULL, 
    [Edition] VARCHAR(50) NULL, 
    [EngineEdition] VARCHAR(50) NULL, 
    [IsClustered] BIT NULL, 
    [NetName] VARCHAR(50) NULL, 
    [OSVersion] VARCHAR(50) NULL,
	[PerfMonMode] VARCHAR(20) NULL,
    [PhysicalMemory] INT NULL, 
    [Platform] VARCHAR(50) NULL, 
    [Processors] INT NULL, 
    [Product] VARCHAR(50) NULL, 
    [ProductLevel] VARCHAR(50) NULL, 
    [ServiceInstanceId] VARCHAR(50) NULL, 
    [ServiceName] VARCHAR(50) NULL, 
    [ServiceAccount] VARCHAR(50) NULL, 
	[Status] VARCHAR(20) NULL,
    [Version] VARCHAR(50) NULL, 
    [IsMonitored] BIT NULL DEFAULT 0, 
    [ExpandContent] BIT NULL DEFAULT 0, 
    [ExpandStorage] BIT NULL DEFAULT 0, 
    [ExpandJobs] BIT NULL DEFAULT 0, 
    [ExpandLogins] BIT NULL DEFAULT 0,
    [ExpandServerRoles] BIT NULL DEFAULT 0,
    [ExpandTriggers] BIT NULL DEFAULT 0,
    [DefaultDatabaseExpandMask] INT NOT NULL DEFAULT 0, 
    CONSTRAINT [PK_Instances] PRIMARY KEY ([ID]),
	CONSTRAINT [FK_Instances_Servers] FOREIGN KEY ([Server_ID]) REFERENCES [dbo].[Servers] ([id])
)
