'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://MyCompany.com", ConfigurationName:="ServiceReference1.ILiveView")>  _
    Public Interface ILiveView
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://MyCompany.com/ILiveView/DisplayLogEntry", ReplyAction:="http://MyCompany.com/ILiveView/DisplayLogEntryResponse")>  _
        Sub DisplayLogEntry(ByVal message As String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ILiveViewChannel
        Inherits ServiceReference1.ILiveView, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LiveViewClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ILiveView)
        Implements ServiceReference1.ILiveView
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DisplayLogEntry(ByVal message As String) Implements ServiceReference1.ILiveView.DisplayLogEntry
            MyBase.Channel.DisplayLogEntry(message)
        End Sub
    End Class
End Namespace
