//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABC
    {
        public decimal COSTREC { get; set; }
        public Nullable<decimal> DLABOR { get; set; }
        public Nullable<decimal> NONTRACE { get; set; }
        public Nullable<decimal> TCOST1 { get; set; }
        public Nullable<decimal> TCOST2 { get; set; }
        public Nullable<decimal> TCOST3 { get; set; }
        public Nullable<decimal> TCOST4 { get; set; }
        public Nullable<decimal> TCOST5 { get; set; }
        public Nullable<decimal> TCOST6 { get; set; }
        public Nullable<decimal> TCOST7 { get; set; }
        public Nullable<decimal> TCOST8 { get; set; }
        public Nullable<decimal> TCOST9 { get; set; }
        public Nullable<decimal> TCOST10 { get; set; }
        public Nullable<decimal> TCOST11 { get; set; }
        public string TYPE1 { get; set; }
        public string TYPE2 { get; set; }
        public string TYPE3 { get; set; }
        public string TYPE4 { get; set; }
        public string TYPE5 { get; set; }
        public string TYPE6 { get; set; }
        public string TYPE7 { get; set; }
        public string TYPE8 { get; set; }
        public string TYPE9 { get; set; }
        public string TYPE10 { get; set; }
        public string TYPE11 { get; set; }
    }
}
