//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY
    {
        public decimal ACT { get; set; }
        public string DESCX { get; set; }
        public Nullable<decimal> NET { get; set; }
        public string USERID { get; set; }
        public string NETID { get; set; }
        public Nullable<decimal> NETDATE { get; set; }
    }
}
