//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTLIN
    {
        public decimal ACT { get; set; }
        public decimal SEQ { get; set; }
        public string DESCX { get; set; }
        public Nullable<decimal> TIMEX { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string BUCODE { get; set; }
        public Nullable<decimal> ELETYPE { get; set; }
    }
}
