//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANNERMESSAGE
    {
        public decimal MSGID { get; set; }
        public string MESSAGETEXT { get; set; }
        public string RAISEDBY { get; set; }
        public string APPROVEDBY { get; set; }
        public string MESSAGEREASON { get; set; }
        public string MESSAGETYPE { get; set; }
        public Nullable<decimal> LINEID { get; set; }
        public string STATIONFROM { get; set; }
        public string STATIONTO { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> LASTUPDATED { get; set; }
        public Nullable<decimal> MESSAGESTATUS { get; set; }
    }
}
