//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_operator
    {
        public decimal ClockNO { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string WWID { get; set; }
        public string SkillLevel { get; set; }
        public Nullable<decimal> LineID { get; set; }
        public Nullable<decimal> PlantID { get; set; }
        public string Passwordx { get; set; }
        public Nullable<decimal> RoleX { get; set; }
    }
}
