//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_operator_track
    {
        public decimal LineID { get; set; }
        public Nullable<decimal> PlantID { get; set; }
        public string StationNO { get; set; }
        public Nullable<decimal> ClockNO { get; set; }
        public decimal LoginSeq { get; set; }
        public string TeamFlag { get; set; }
        public System.DateTime LoginDate { get; set; }
        public Nullable<System.DateTime> LogoutDate { get; set; }
        public Nullable<decimal> StationPosition { get; set; }
    }
}
