//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_team
    {
        public Nullable<decimal> PlantID { get; set; }
        public decimal TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamDesc { get; set; }
    }
}
