//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPPOPHDR7
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public string OPNO { get; set; }
        public Nullable<decimal> WAITIME { get; set; }
        public Nullable<decimal> TRAVEL { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public string USERDEF4 { get; set; }
        public string USERDEF5 { get; set; }
        public string USERDEF6 { get; set; }
        public string USERDEF7 { get; set; }
        public string USERDEF8 { get; set; }
        public string USERDEF9 { get; set; }
        public string USERDEF10 { get; set; }
    }
}
