//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public decimal KEYX { get; set; }
        public string DATA { get; set; }
        public Nullable<short> WL { get; set; }
        public Nullable<short> L { get; set; }
        public Nullable<short> TYPE { get; set; }
        public Nullable<short> DP { get; set; }
    }
}
