//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class COST
    {
        public decimal COSTREC { get; set; }
        public Nullable<decimal> OH { get; set; }
        public Nullable<decimal> LABOR { get; set; }
        public Nullable<decimal> BURDEN { get; set; }
        public Nullable<decimal> SCRAP { get; set; }
        public Nullable<decimal> INDLABOR { get; set; }
        public string COSTDESC { get; set; }
    }
}
