//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumminsWI_DefectSBM
    {
        public string Engine_Serial_No { get; set; }
        public string StationNO { get; set; }
        public string Component_Item_No { get; set; }
        public decimal MSeq { get; set; }
        public string Primary_item_no { get; set; }
        public string Option_No { get; set; }
        public string MSBM_Code { get; set; }
        public string Shop_Order_No { get; set; }
        public string Unit_No { get; set; }
        public string Component_Description { get; set; }
        public string ID_Code { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Item_Indent_Flag { get; set; }
        public Nullable<System.DateTime> DateX { get; set; }
        public string OperatorX { get; set; }
        public string CommentX { get; set; }
        public string CategoryX { get; set; }
        public string PartSerialNo { get; set; }
        public string UserDef1 { get; set; }
        public string UserDef2 { get; set; }
        public string UserDef3 { get; set; }
    }
}
