//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cumminswi_mrc_substationdata
    {
        public decimal EngineNo { get; set; }
        public string StationNO { get; set; }
        public decimal PartID { get; set; }
        public string RecType { get; set; }
        public decimal Seq { get; set; }
        public string OPNO { get; set; }
        public string PartNO { get; set; }
        public Nullable<decimal> StationComplete { get; set; }
        public string ClockNO { get; set; }
        public string SupervisorClockNO { get; set; }
    }
}
