//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cumminswi_mrc_enginelist
    {
        public decimal MRCEngineID { get; set; }
        public decimal LineID { get; set; }
        public Nullable<decimal> OriginalEngineNo { get; set; }
        public Nullable<decimal> TemplateEngineNO { get; set; }
        public string RebuildEngineNo { get; set; }
        public string RebuildLetter { get; set; }
        public string MONumber { get; set; }
        public string EngineUnit { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string StartEngineer { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string EndEngineer { get; set; }
        public decimal MotherPlantCode { get; set; }
        public decimal EngineComplete { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
        public string Spare4 { get; set; }
        public string Spare5 { get; set; }
        public string CurrentStationNO { get; set; }
        public string PercentCompleteX { get; set; }
        public Nullable<System.DateTime> WIPStartDate { get; set; }
    }
}
