//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cumminswi_messages
    {
        public decimal MsgID { get; set; }
        public string MessageText { get; set; }
        public string RaisedBy { get; set; }
        public string ApprovedBY { get; set; }
        public string MessageReason { get; set; }
        public string MessageType { get; set; }
        public Nullable<decimal> LineID { get; set; }
        public string StationFrom { get; set; }
        public string StationTo { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<decimal> MessageStatus { get; set; }
    }
}
