//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentEngineStatu
    {
        public decimal LineID { get; set; }
        public string Line_code { get; set; }
        public string StationNo { get; set; }
        public string ESNInStation { get; set; }
        public Nullable<System.DateTime> EngineMoveDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string SourceMisc { get; set; }
        public string PLCSource { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
        public Nullable<decimal> StationPosition { get; set; }
        public string Process_Flag { get; set; }
    }
}
