//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EASE_NEWFIELD_INTERFACE
    {
        public string EngineNo { get; set; }
        public string StationNo { get; set; }
        public string EASE_PASS_OR_FAIL_FLAG { get; set; }
        public string EASE_MESSAGE_TEXT { get; set; }
        public Nullable<System.DateTime> PASS_TIMESTAMP { get; set; }
        public Nullable<System.DateTime> EASE_TIMESTAMP { get; set; }
        public string NEWFIELD_RETURN_CODE { get; set; }
        public string NEWFIELD_MESSAGE_TEXT { get; set; }
        public Nullable<System.DateTime> NEWFIELD_TIMESTAMP { get; set; }
        public string DEFAULT_STATE { get; set; }
        public string Passed_Checks { get; set; }
        public string Incomplete_Checks { get; set; }
        public string Fail_Checks { get; set; }
        public string Passed_Deviations { get; set; }
        public string InComplete_Deviations { get; set; }
        public string Failed_Deviations { get; set; }
        public string STOPBUILD { get; set; }
        public Nullable<decimal> StationPosition { get; set; }
    }
}
