//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EASEGROUP
    {
        public decimal PLANTID { get; set; }
        public decimal GROUPID { get; set; }
        public string GROUPNAME { get; set; }
        public string MODULES { get; set; }
        public Nullable<decimal> EASEACCESS { get; set; }
        public string PLANRES { get; set; }
        public Nullable<decimal> PLANRESNUM { get; set; }
        public string PLANRES1 { get; set; }
        public Nullable<decimal> PLANRESNUM1 { get; set; }
        public Nullable<decimal> PRINTCONTROLDOC { get; set; }
        public string MISC1 { get; set; }
        public string MISC2 { get; set; }
        public string MISC3 { get; set; }
        public Nullable<decimal> EASEAUTHGROUP { get; set; }
        public string RH_FIELDS { get; set; }
        public string OP_FIELDS { get; set; }
        public Nullable<decimal> MCRCREATOR { get; set; }
        public Nullable<decimal> RFCAPPROVER { get; set; }
        public Nullable<decimal> PROCDOCAPPROVER { get; set; }
        public Nullable<decimal> PROCDOCWriter { get; set; }
        public Nullable<decimal> MDMACCESS { get; set; }
        public string GROUPCODE { get; set; }
        public string LPALAYER { get; set; }
        public Nullable<decimal> LPADAILYAUDIT { get; set; }
        public Nullable<decimal> TOOLMGMTACCESS { get; set; }
    }
}
