//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EASE_ENGINE_OPTIONS_VW
    {
        public decimal Line_ID { get; set; }
        public string Line_code { get; set; }
        public string Engine_Serial_No { get; set; }
        public string Option_No { get; set; }
        public string Option_Description { get; set; }
        public string MSBM_Code { get; set; }
        public string Engine_Location { get; set; }
        public string Shop_Order_No { get; set; }
        public string Unit_No { get; set; }
        public string Engine_Model { get; set; }
        public Nullable<System.DateTime> Explode_Date { get; set; }
    }
}
