//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERGOLIN
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public string OPNO { get; set; }
        public decimal ESEQ { get; set; }
        public string BODYPART { get; set; }
        public Nullable<decimal> EFFORT { get; set; }
        public Nullable<decimal> CONTINUOUS { get; set; }
        public Nullable<decimal> EFFORTPERMIN { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public Nullable<decimal> SPARE { get; set; }
    }
}
