//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EUSERRIGHT
    {
        public string USERID { get; set; }
        public decimal PLANTID { get; set; }
        public Nullable<decimal> GROUPID { get; set; }
        public string MODULES { get; set; }
        public Nullable<decimal> EASEACCESS { get; set; }
        public Nullable<decimal> MDMACCESS { get; set; }
        public string PLANRES { get; set; }
        public Nullable<decimal> PLANRESNUM { get; set; }
        public string PLANRES1 { get; set; }
        public Nullable<decimal> PLANRESNUM1 { get; set; }
        public Nullable<decimal> PRINTCONTROLDOC { get; set; }
        public string MISC1 { get; set; }
        public string MISC2 { get; set; }
        public string MISC3 { get; set; }
        public Nullable<decimal> LPAALTERNATEMANAGER { get; set; }
        public Nullable<decimal> TOOLMGMTACCESS { get; set; }
    }
}
