//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EUSER
    {
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORDX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> EXPIRYDATE { get; set; }
        public Nullable<decimal> LOGGEDONEASE { get; set; }
        public Nullable<decimal> ADMINGROUPID { get; set; }
        public string MISC1 { get; set; }
        public string MISC2 { get; set; }
        public string MISC3 { get; set; }
        public Nullable<decimal> USERDISABLED { get; set; }
    }
}
