//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULA
    {
        public string BUCODE { get; set; }
        public string DESCX { get; set; }
        public string QUEST1 { get; set; }
        public string QUEST2 { get; set; }
        public string QUEST3 { get; set; }
        public string QUEST4 { get; set; }
        public string QUEST5 { get; set; }
        public string QUEST6 { get; set; }
        public string QUEST7 { get; set; }
        public string QUEST8 { get; set; }
        public string QUEST9 { get; set; }
        public string QUEST10 { get; set; }
        public string FORM { get; set; }
        public Nullable<decimal> NET { get; set; }
    }
}
