//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMATTEDHISTORY
    {
        public decimal ID { get; set; }
        public decimal ENTRYSEQ { get; set; }
        public decimal ENTRYDATE { get; set; }
        public string REV { get; set; }
        public string ENG { get; set; }
        public string PCNECN { get; set; }
        public string OPNO { get; set; }
        public Nullable<decimal> OPNOVAL { get; set; }
        public decimal COMMENTSEQ { get; set; }
        public string COMMENTx { get; set; }
        public string Reason { get; set; }
        public string OpRev { get; set; }
        public Nullable<decimal> EffectOnStd { get; set; }
    }
}
