//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENERICOPTION
    {
        public int OPTIONID { get; set; }
        public string OPTIONCODE { get; set; }
        public string OPTIONNAME { get; set; }
    }
}
