//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HITACHIEBSEXPORT
    {
        public decimal ID { get; set; }
        public string EBSLOCATION { get; set; }
        public string FILENAME { get; set; }
        public System.DateTime EXPORTDATE { get; set; }
        public string ENGINEER { get; set; }
        public decimal EXPORTTYPE { get; set; }
        public string ASSEMBLIESLOCATION { get; set; }
        public System.DateTime EFFECTIVITYDATE { get; set; }
        public string APRISOLOCATION { get; set; }
    }
}
