//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KVI
    {
        public decimal KVIID { get; set; }
        public string KVIDESCRIPTION { get; set; }
        public string KVI1 { get; set; }
        public string KVI2 { get; set; }
        public string KVI3 { get; set; }
        public string KVI4 { get; set; }
        public string KVI5 { get; set; }
        public string KVI6 { get; set; }
        public string KVI7 { get; set; }
        public string KVI8 { get; set; }
        public string KVI9 { get; set; }
        public string KVI10 { get; set; }
        public string KVI11 { get; set; }
        public string KVI12 { get; set; }
        public string KVI13 { get; set; }
        public string KVI14 { get; set; }
        public string KVI15 { get; set; }
        public string KVI16 { get; set; }
        public string KVI17 { get; set; }
        public string KVI18 { get; set; }
        public string KVI19 { get; set; }
        public string KVI20 { get; set; }
        public string KVI21 { get; set; }
        public string KVI22 { get; set; }
        public string KVI23 { get; set; }
        public string KVI24 { get; set; }
        public string KVI25 { get; set; }
        public string KVI26 { get; set; }
        public string KVI27 { get; set; }
        public string KVI28 { get; set; }
        public string KVI29 { get; set; }
        public string KVI30 { get; set; }
        public string KVI31 { get; set; }
        public string KVI32 { get; set; }
        public string KVI33 { get; set; }
        public string KVI34 { get; set; }
        public string KVI35 { get; set; }
        public string KVI36 { get; set; }
        public string KVI37 { get; set; }
        public string KVI38 { get; set; }
        public string KVI39 { get; set; }
        public string KVI40 { get; set; }
        public string KVIID1 { get; set; }
        public string KVIID2 { get; set; }
        public string KVIID3 { get; set; }
        public string KVIID4 { get; set; }
        public string KVIID5 { get; set; }
        public string KVIID6 { get; set; }
        public string KVIID7 { get; set; }
        public string KVIID8 { get; set; }
        public string KVIID9 { get; set; }
        public string KVIID10 { get; set; }
        public string KVIID11 { get; set; }
        public string KVIID12 { get; set; }
        public string KVIID13 { get; set; }
        public string KVIID14 { get; set; }
        public string KVIID15 { get; set; }
        public string KVIID16 { get; set; }
        public string KVIID17 { get; set; }
        public string KVIID18 { get; set; }
        public string KVIID19 { get; set; }
        public string KVIID20 { get; set; }
        public string KVIID21 { get; set; }
        public string KVIID22 { get; set; }
        public string KVIID23 { get; set; }
        public string KVIID24 { get; set; }
        public string KVIID25 { get; set; }
        public string KVIID26 { get; set; }
        public string KVIID27 { get; set; }
        public string KVIID28 { get; set; }
        public string KVIID29 { get; set; }
        public string KVIID30 { get; set; }
        public string KVIID31 { get; set; }
        public string KVIID32 { get; set; }
        public string KVIID33 { get; set; }
        public string KVIID34 { get; set; }
        public string KVIID35 { get; set; }
        public string KVIID36 { get; set; }
        public string KVIID37 { get; set; }
        public string KVIID38 { get; set; }
        public string KVIID39 { get; set; }
        public string KVIID40 { get; set; }
    }
}
