//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBCATLOG
    {
        public string CATKEY { get; set; }
        public string LINENOLB { get; set; }
        public string GRAPHIC { get; set; }
        public Nullable<decimal> DATEX { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> TAKT { get; set; }
        public Nullable<decimal> NETFLAG { get; set; }
        public string LBINDEX { get; set; }
        public Nullable<decimal> XQUOTA { get; set; }
        public Nullable<decimal> XAVAILABLEHOURS { get; set; }
        public Nullable<decimal> XEFFICENCY { get; set; }
        public Nullable<decimal> ModelMix1 { get; set; }
        public Nullable<decimal> ModelMix2 { get; set; }
        public Nullable<decimal> ModelMix3 { get; set; }
        public Nullable<decimal> ModelMix4 { get; set; }
        public Nullable<decimal> ModelMix5 { get; set; }
        public Nullable<decimal> ModelMix6 { get; set; }
        public Nullable<decimal> ModelMix7 { get; set; }
        public Nullable<decimal> ModelMix8 { get; set; }
        public Nullable<decimal> ModelMix9 { get; set; }
        public Nullable<decimal> ModelMix10 { get; set; }
        public Nullable<decimal> ModelMix11 { get; set; }
        public Nullable<decimal> ModelMix12 { get; set; }
        public Nullable<decimal> ModelMix13 { get; set; }
        public Nullable<decimal> ModelMix14 { get; set; }
        public Nullable<decimal> ModelMix15 { get; set; }
        public Nullable<decimal> ModelMix16 { get; set; }
        public Nullable<decimal> ModelMix17 { get; set; }
        public Nullable<decimal> ModelMix18 { get; set; }
        public Nullable<decimal> ModelMix19 { get; set; }
        public Nullable<decimal> ModelMix20 { get; set; }
        public Nullable<decimal> ModelMix21 { get; set; }
        public Nullable<decimal> ModelMix22 { get; set; }
        public Nullable<decimal> ModelMix23 { get; set; }
        public Nullable<decimal> ModelMix24 { get; set; }
        public Nullable<decimal> ModelMix25 { get; set; }
        public Nullable<decimal> ModelMix26 { get; set; }
        public Nullable<decimal> ModelMix27 { get; set; }
        public Nullable<decimal> ModelMix28 { get; set; }
        public Nullable<decimal> ModelMix29 { get; set; }
        public Nullable<decimal> ModelMix30 { get; set; }
        public Nullable<decimal> ModelMix31 { get; set; }
        public Nullable<decimal> ModelMix32 { get; set; }
        public Nullable<decimal> Spare { get; set; }
        public Nullable<decimal> NonProdMins { get; set; }
        public string ENGINEER { get; set; }
        public string MODELYEAR { get; set; }
        public Nullable<decimal> PlantModelID { get; set; }
        public Nullable<decimal> PLANTID { get; set; }
    }
}
