//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LBPART
    {
        public string LBPARTSKEY { get; set; }
        public decimal SEQ { get; set; }
        public string PARTNUMBER { get; set; }
        public string ALLOCATED { get; set; }
        public string NUMOPS { get; set; }
        public Nullable<decimal> WAITTOTAL { get; set; }
        public Nullable<decimal> HISTATRUN { get; set; }
        public string FILENAME { get; set; }
        public string RECTYPE { get; set; }
        public Nullable<decimal> SEQNUM { get; set; }
        public string DESCX { get; set; }
        public Nullable<decimal> MIX { get; set; }
    }
}
