//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHHDR
    {
        public decimal MACH { get; set; }
        public string ID { get; set; }
        public string DESCX { get; set; }
        public Nullable<decimal> MANUALNC { get; set; }
        public Nullable<decimal> DATAGRP { get; set; }
        public string DEPT { get; set; }
        public Nullable<decimal> MGROUP { get; set; }
        public Nullable<decimal> MAXHP { get; set; }
        public Nullable<decimal> RIGIDITY { get; set; }
        public string AQDATE { get; set; }
        public Nullable<decimal> BASTIME { get; set; }
        public Nullable<decimal> TOOLTIME { get; set; }
        public Nullable<decimal> INITTIME { get; set; }
        public Nullable<decimal> SUBTIME { get; set; }
        public string ELEMENT1 { get; set; }
        public string ELEMENT2 { get; set; }
        public string ELEMENT3 { get; set; }
        public string ELEMENT4 { get; set; }
        public Nullable<decimal> AXIS { get; set; }
        public Nullable<decimal> DETCNT { get; set; }
        public Nullable<decimal> SPINDLES { get; set; }
        public Nullable<decimal> NET { get; set; }
    }
}
