//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFT
    {
        public string BUCODE { get; set; }
        public string DESCX { get; set; }
        public Nullable<decimal> TIMEX { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> NET { get; set; }
        public string USERID { get; set; }
        public Nullable<decimal> ELEDATE { get; set; }
        public string ENGINEER { get; set; }
        public string SIGNOFF { get; set; }
        public string VIDEOFILE { get; set; }
        public string COMPARISON { get; set; }
        public Nullable<decimal> ANNUALRATE { get; set; }
        public Nullable<decimal> LABORRATE { get; set; }
        public string USERDEF1 { get; set; }
        public Nullable<decimal> INVESTMENT { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public Nullable<decimal> REVNUMBER { get; set; }
    }
}
