//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODBCDATA
    {
        public decimal KEYX { get; set; }
        public Nullable<decimal> FIELDNUM { get; set; }
        public string DATASOURCE { get; set; }
        public string ODBCTABLE { get; set; }
        public string ODBCFIELD { get; set; }
        public Nullable<decimal> ADDTNLFIELD1 { get; set; }
        public string ADDTNLNAME1 { get; set; }
        public Nullable<decimal> ADDTNLFIELD2 { get; set; }
        public string ADDTNLNAME2 { get; set; }
        public Nullable<decimal> ADDTNLFIELD3 { get; set; }
        public string ADDTNLNAME3 { get; set; }
        public string SQLQUERY { get; set; }
        public string USERDEFNAME { get; set; }
        public string ABBRV1 { get; set; }
        public string ABBRV2 { get; set; }
        public string ABBRV3 { get; set; }
        public Nullable<decimal> EDITFLAG { get; set; }
        public Nullable<decimal> XVISIBLE { get; set; }
        public Nullable<decimal> XREQUIRED { get; set; }
        public string USERDEFDEFAULT { get; set; }
        public Nullable<decimal> PLANTID { get; set; }
    }
}
