//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPAUTHCNT
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public string OPNO { get; set; }
        public string OPREV { get; set; }
        public Nullable<decimal> NUMSIGN { get; set; }
        public Nullable<decimal> DONESIGN { get; set; }
        public string AUTHSTATUS { get; set; }
        public Nullable<decimal> AWAITINGCHECKIN { get; set; }
        public Nullable<decimal> PENDINGDATE { get; set; }
    }
}
