//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPHDR
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public decimal OPSEQ { get; set; }
        public string OPNO { get; set; }
        public string OPDESC { get; set; }
        public string WORKCENT { get; set; }
        public Nullable<decimal> MAXBATCH { get; set; }
        public Nullable<decimal> DATAREC { get; set; }
        public Nullable<decimal> PFDCYC { get; set; }
        public Nullable<decimal> PFDSETUP { get; set; }
        public Nullable<decimal> REALCYC { get; set; }
        public Nullable<decimal> REALSETUP { get; set; }
        public Nullable<decimal> ACOSTRATE { get; set; }
        public Nullable<decimal> ACYCTIME { get; set; }
        public Nullable<decimal> ASETUPTIME { get; set; }
        public Nullable<decimal> MATRECNO { get; set; }
        public Nullable<decimal> MACHRECNO { get; set; }
        public Nullable<decimal> EffectiveFrom { get; set; }
        public Nullable<decimal> ISMETRIC { get; set; }
        public Nullable<decimal> MISCFLAG1 { get; set; }
        public Nullable<decimal> PCNNO { get; set; }
        public Nullable<decimal> MISCFLAG2 { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public Nullable<decimal> TOOLCOSTRUN { get; set; }
        public Nullable<decimal> TOOLCOSTSU { get; set; }
        public Nullable<decimal> NSL { get; set; }
        public string PROCESSFLAG { get; set; }
        public Nullable<decimal> NOMEN { get; set; }
        public Nullable<decimal> BALANCEFLAG { get; set; }
        public Nullable<decimal> ALTFLAG { get; set; }
        public Nullable<decimal> COSTKEY { get; set; }
        public Nullable<decimal> RULEID { get; set; }
        public Nullable<decimal> STATIONTIME { get; set; }
        public string Engineer { get; set; }
        public Nullable<decimal> ReleasedFlag { get; set; }
        public Nullable<decimal> InUseFlag { get; set; }
        public Nullable<decimal> CRITOPTIME { get; set; }
        public string CRITOP { get; set; }
        public Nullable<decimal> VA { get; set; }
        public Nullable<decimal> NVA { get; set; }
        public Nullable<decimal> ESSNVA { get; set; }
        public string OpRev { get; set; }
        public string CheckOut_Engineer { get; set; }
        public Nullable<decimal> OpRelDate { get; set; }
        public Nullable<decimal> EffectiveTo { get; set; }
        public string SPARE1 { get; set; }
        public string SPARE2 { get; set; }
        public string SPARE3 { get; set; }
        public Nullable<decimal> SHAREDOPID { get; set; }
        public Nullable<decimal> BasicRunTime { get; set; }
        public Nullable<decimal> BasicSetupTime { get; set; }
        public string KVICODE { get; set; }
    }
}
