//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPHPFD
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public string OPNO { get; set; }
        public Nullable<decimal> FORCELB { get; set; }
        public Nullable<decimal> FORCEPTS { get; set; }
        public string FORCELMH { get; set; }
        public Nullable<decimal> FORCESTART { get; set; }
        public Nullable<decimal> ALLOWANCE { get; set; }
        public Nullable<decimal> POSTUREPTS { get; set; }
        public string POSTURELMH { get; set; }
        public Nullable<decimal> POSTURESTART { get; set; }
        public Nullable<decimal> VIBRATIONPTS { get; set; }
        public string VIBRATIONLMH { get; set; }
        public Nullable<decimal> VIBRATIONSTA { get; set; }
        public Nullable<decimal> SHRTCYCPTS { get; set; }
        public string SHRTCYCLMH { get; set; }
        public Nullable<decimal> SHRTCYCSTART { get; set; }
        public Nullable<decimal> CLOTHINGPTS { get; set; }
        public string CLOTHINGLMH { get; set; }
        public Nullable<decimal> CLOTHSTART { get; set; }
        public Nullable<decimal> CONCENPTS { get; set; }
        public string CONCENLMH { get; set; }
        public Nullable<decimal> CONCENSTART { get; set; }
        public Nullable<decimal> MONOTONYPTS { get; set; }
        public string MONOTONYLMH { get; set; }
        public Nullable<decimal> MONOTONYSTRT { get; set; }
        public Nullable<decimal> EYESTRPTS { get; set; }
        public string EYESTRLMH { get; set; }
        public Nullable<decimal> EYESTRSTART { get; set; }
        public Nullable<decimal> NOISEPTS { get; set; }
        public string NOISELMH { get; set; }
        public Nullable<decimal> NOISESTART { get; set; }
        public Nullable<decimal> HUMIDITYPTS { get; set; }
        public string HUMIDITYLMH { get; set; }
        public Nullable<decimal> HUMIDITYSTRT { get; set; }
        public Nullable<decimal> TEMPERVAL { get; set; }
        public Nullable<decimal> VENTPTS { get; set; }
        public string VENTLMH { get; set; }
        public Nullable<decimal> VENTSTART { get; set; }
        public Nullable<decimal> FUMESPTS { get; set; }
        public string FUMESLMH { get; set; }
        public Nullable<decimal> FUMESSTART { get; set; }
        public Nullable<decimal> DUSTPTS { get; set; }
        public string DUSTLMH { get; set; }
        public Nullable<decimal> DUSTSTART { get; set; }
        public Nullable<decimal> DIRTPTS { get; set; }
        public string DIRTLMH { get; set; }
        public Nullable<decimal> DIRTSTART { get; set; }
        public Nullable<decimal> WETPTS { get; set; }
        public string WETLMH { get; set; }
        public Nullable<decimal> WETSTART { get; set; }
    }
}
