//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPMACHINE
    {
        public decimal SHID { get; set; }
        public decimal MACHSEQ { get; set; }
        public string MACHNUMBER { get; set; }
        public string MACHDESCX { get; set; }
        public Nullable<decimal> MACHRUNTIME { get; set; }
        public string MACHFLAG { get; set; }
        public string SPARE { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public string pallet { get; set; }
        public Nullable<decimal> VisualAid { get; set; }
        public Nullable<decimal> VisualAid1 { get; set; }
        public string cell { get; set; }
    }
}
