//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNAUTHGROUP
    {
        public decimal QID { get; set; }
        public decimal GROUPID { get; set; }
        public Nullable<decimal> NOTIFYFLAG { get; set; }
        public Nullable<decimal> AUTHFLAG { get; set; }
    }
}
