//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNCHANGETEXT
    {
        public string PCNNO { get; set; }
        public decimal CHANGETYPE { get; set; }
        public string CHANGETEXT { get; set; }
        public decimal CHANGETEXTSEQ { get; set; }
    }
}
