//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNMM
    {
        public string PCNNO { get; set; }
        public Nullable<decimal> MSEQ { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATHX { get; set; }
        public Nullable<decimal> WPTYPE { get; set; }
        public decimal TTKEY { get; set; }
        public string DOCDESC { get; set; }
        public string FILEDESCX { get; set; }
        public Nullable<decimal> VISUALAID { get; set; }
    }
}
