//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNRFCCAT
    {
        public decimal GROUPID { get; set; }
        public decimal CATEGORYID { get; set; }
        public decimal SEQ_ { get; set; }
        public string CATEGORYNAME { get; set; }
    }
}
