//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNSD
    {
        public string PCNNO { get; set; }
        public decimal PCNKey { get; set; }
        public decimal DocID { get; set; }
        public string DocDesc { get; set; }
        public string RevNumber { get; set; }
        public decimal DocSeq { get; set; }
        public string ApprovedStatus { get; set; }
        public Nullable<decimal> LocationDoc { get; set; }
        public string KeyFieldValue { get; set; }
    }
}
