//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNSDAUTHCNT
    {
        public decimal DocID { get; set; }
        public decimal DocSeq { get; set; }
        public Nullable<decimal> NUMSIGN { get; set; }
        public Nullable<decimal> DONESIGN { get; set; }
        public string AUTHSTATUS { get; set; }
        public Nullable<decimal> AWAITINGCHECKIN { get; set; }
        public Nullable<decimal> PENDINGDATE { get; set; }
        public Nullable<decimal> LocationDoc { get; set; }
    }
}
