//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNSDAuth
    {
        public decimal DocID { get; set; }
        public decimal DocSeq { get; set; }
        public Nullable<decimal> GROUPID { get; set; }
        public string AUTHORIZER { get; set; }
        public Nullable<decimal> AUTHDATE { get; set; }
        public string AUTHSTATUS { get; set; }
        public string COMMENTX { get; set; }
        public Nullable<decimal> LocationDoc { get; set; }
    }
}
