//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNTASK
    {
        public string PCNNO { get; set; }
        public decimal TEMPLATEID { get; set; }
        public Nullable<decimal> GROUPID { get; set; }
        public decimal MSEQ { get; set; }
        public string DESCX { get; set; }
        public string APPROVERID { get; set; }
        public Nullable<decimal> DUEDATE { get; set; }
        public decimal APPLICABLE { get; set; }
        public decimal CRITICAL { get; set; }
        public string TASKSTATUS { get; set; }
        public Nullable<decimal> SignoffDate { get; set; }
        public string UserRole { get; set; }
        public string Manager { get; set; }
        public Nullable<decimal> EscalateDATE { get; set; }
        public Nullable<decimal> TaskSeq { get; set; }
        public string COMMENTX { get; set; }
        public Nullable<decimal> SEVERITY { get; set; }
    }
}
