//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNTASKLIST
    {
        public decimal PLANTID { get; set; }
        public decimal TEMPLATEID { get; set; }
        public Nullable<decimal> GROUPID { get; set; }
        public string USERID { get; set; }
        public string UserRole { get; set; }
        public string Manager { get; set; }
        public string TaskDesc { get; set; }
        public Nullable<decimal> Critical { get; set; }
        public Nullable<decimal> TaskNum { get; set; }
    }
}
