//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNTASKDueDateChanx
    {
        public string PCNNO { get; set; }
        public decimal MSEQ { get; set; }
        public string TaskDESCX { get; set; }
        public decimal TaskSEQ { get; set; }
        public Nullable<decimal> DATEX { get; set; }
        public Nullable<decimal> OldDATEX { get; set; }
        public Nullable<decimal> NewDATEX { get; set; }
        public string CommentX { get; set; }
        public string ChangedBy { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
    }
}
