//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCNTASKEscalate
    {
        public string PCNNO { get; set; }
        public Nullable<decimal> GROUPID { get; set; }
        public decimal MSEQ { get; set; }
        public string TASKDESCX { get; set; }
        public string ManagerID { get; set; }
        public Nullable<decimal> DUEDATE { get; set; }
        public Nullable<decimal> EscalateDATE { get; set; }
        public string REASONX { get; set; }
    }
}
