//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMCPLINE
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public decimal LINESEQ { get; set; }
        public Nullable<decimal> PROCESSSEQ { get; set; }
        public string MACHINE { get; set; }
        public string FEATURENUMBER { get; set; }
        public string PRODUCTTEXT { get; set; }
        public string PROCESSTEXT { get; set; }
        public string SPECIALCHAR { get; set; }
        public string SPECTOLERANCE { get; set; }
        public string EVALMETHOD { get; set; }
        public string ECODE { get; set; }
        public string EVALTOOL { get; set; }
        public string SAMPLESIZE { get; set; }
        public string SAMPLEFREQ { get; set; }
        public string CONTROLMETHOD { get; set; }
        public string CMCODE { get; set; }
        public string REACTIONPLAN { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public string PRINTFLAG { get; set; }
    }
}
