//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMDETCODE
    {
        public decimal DETNUMBER { get; set; }
        public string DETDESC { get; set; }
        public string DETCOMMENT { get; set; }
        public string LIKELIHOOD { get; set; }
    }
}
