//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMErgoAudit
    {
        public string WorkGroupID { get; set; }
        public string WC { get; set; }
        public Nullable<short> ErgoClass { get; set; }
        public Nullable<short> ItemKey { get; set; }
        public string ItemStatus { get; set; }
        public Nullable<decimal> ItemScore { get; set; }
        public string Comments { get; set; }
        public short Seq { get; set; }
    }
}
