//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMErgoHdr
    {
        public string WorkGroupID { get; set; }
        public string WC { get; set; }
        public string Engineer { get; set; }
        public Nullable<int> HeavyLift { get; set; }
        public Nullable<int> NIOSHRec { get; set; }
        public Nullable<int> WeightLimit { get; set; }
        public Nullable<int> LiftingIndex { get; set; }
        public Nullable<short> StrainScore { get; set; }
        public Nullable<short> TherapyScore { get; set; }
        public Nullable<short> EJMSscore { get; set; }
        public string Comments { get; set; }
        public Nullable<short> WeightedScore { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<decimal> Datex { get; set; }
        public Nullable<short> Net { get; set; }
        public int Seq { get; set; }
        public Nullable<short> EJMSscore2 { get; set; }
    }
}
