//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMFMEAHistory
    {
        public decimal docid { get; set; }
        public string docrectype { get; set; }
        public decimal docseq { get; set; }
        public decimal entryseq { get; set; }
        public decimal commentseq { get; set; }
        public Nullable<decimal> entrydate { get; set; }
        public string rev { get; set; }
        public string eng { get; set; }
        public string commentx { get; set; }
        public Nullable<decimal> commentflag { get; set; }
    }
}
