//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMFMEACPHDR
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public string ITEM { get; set; }
        public string KEYCONTACT { get; set; }
        public string MODELYEAR { get; set; }
        public Nullable<decimal> KEYDATE { get; set; }
        public string FMEACPNO { get; set; }
        public Nullable<decimal> ORIGDATE { get; set; }
        public Nullable<decimal> REVDATE { get; set; }
        public string REVNUMBER { get; set; }
        public string SUPPLIER { get; set; }
        public string SUPPLIERCODE { get; set; }
        public string SUPPLIERAPPROVER { get; set; }
        public Nullable<decimal> SUPPLIERAPPDATE { get; set; }
        public string CUSTENGAPPROVER { get; set; }
        public Nullable<decimal> CUSTENGAPPDATE { get; set; }
        public string CUSTQCAPPROVER { get; set; }
        public Nullable<decimal> CUSTQCAPPDATE { get; set; }
        public string OTHERAPPROVER { get; set; }
        public Nullable<decimal> OTHERAPPDATE { get; set; }
        public Nullable<decimal> STATUSFLAG { get; set; }
        public string DFMEANO { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public string PREPAREDBY { get; set; }
        public Nullable<decimal> ControlPlanType { get; set; }
        public string PhoneNo { get; set; }
        public string PartDesc { get; set; }
        public Nullable<decimal> PERCENTRED { get; set; }
        public string ME_HANDOVER { get; set; }
        public string USERDEF1_FMEA { get; set; }
        public string USERDEF2_FMEA { get; set; }
        public string USERDEF3_FMEA { get; set; }
        public string KEYCONTACTID { get; set; }
        public string WARRANTYDATERANGE { get; set; }
        public string BISDATERANGE { get; set; }
        public Nullable<decimal> TEMPLATEID { get; set; }
        public string KEYCONTACT_MQV { get; set; }
        public string KEYCONTACTID_MQV { get; set; }
        public string PHONENO_MQV { get; set; }
        public string USERDEF1_MQV { get; set; }
        public string USERDEF2_MQV { get; set; }
        public string USERDEF3_MQV { get; set; }
        public string USERDEF1_DEFECTMODE { get; set; }
        public string USERDEF2_DEFECTMODE { get; set; }
        public string USERDEF3_DEFECTMODE { get; set; }
        public string USERDEF4_DEFECTMODE { get; set; }
        public string USERDEF5_DEFECTMODE { get; set; }
        public string USERDEF6_DEFECTMODE { get; set; }
        public string USERDEF7_DEFECTMODE { get; set; }
        public string USERDEF8_DEFECTMODE { get; set; }
        public string USERDEF9_DEFECTMODE { get; set; }
        public string USERDEF10_DEFECTMODE { get; set; }
        public string KEYCONTACT_CP { get; set; }
        public string KEYCONTACTID_CP { get; set; }
        public string PHONENO_CP { get; set; }
        public string USERDEF1_CP { get; set; }
        public string USERDEF2_CP { get; set; }
        public string USERDEF3_CP { get; set; }
        public string ME_COMPLETE { get; set; }
        public string QC_COMPLETE { get; set; }
        public Nullable<decimal> ME_COMPLETEDATE { get; set; }
        public Nullable<decimal> QC_COMPLETEDATE { get; set; }
    }
}
