//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMFAILEFFECTCODE
    {
        public decimal FAILEFFECTID { get; set; }
        public string FAILEFFECTCODE { get; set; }
        public Nullable<decimal> FAILEFFECTNUMBER { get; set; }
        public string FAILEFFECTDESC { get; set; }
    }
}
