//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMFMEALINE
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public decimal LINESEQ { get; set; }
        public Nullable<decimal> PROCESSSEQ { get; set; }
        public string POTENFAILMODE { get; set; }
        public string PFMCODE { get; set; }
        public Nullable<decimal> LEVELSEQ { get; set; }
        public string POTENEFFECT { get; set; }
        public string PECODE { get; set; }
        public Nullable<decimal> SPARE1 { get; set; }
        public Nullable<decimal> SEVERITY { get; set; }
        public string CLASS { get; set; }
        public string POTENCAUSE { get; set; }
        public string PCCODE { get; set; }
        public Nullable<decimal> SPARE2 { get; set; }
        public Nullable<decimal> OCCURENCE { get; set; }
        public string CPCPREVENTION { get; set; }
        public string CPCPCODE { get; set; }
        public string CPCDETECTION { get; set; }
        public string CPCDCODE { get; set; }
        public Nullable<decimal> DETECTION { get; set; }
        public Nullable<decimal> RPN { get; set; }
        public string RECOMMENDEDACTION { get; set; }
        public string RESPARTY { get; set; }
        public Nullable<decimal> COMPLETIONDATE { get; set; }
        public string ACTIONTAKEN { get; set; }
        public Nullable<decimal> NEWSEV { get; set; }
        public Nullable<decimal> NEWOCC { get; set; }
        public Nullable<decimal> NEWDET { get; set; }
        public Nullable<decimal> NEWRPN { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public Nullable<decimal> LPAAUDITREQUIRED { get; set; }
        public Nullable<decimal> LPADOCID { get; set; }
        public string LPADOCRECTYPE { get; set; }
        public Nullable<decimal> LPADOCSEQ { get; set; }
        public Nullable<decimal> LPAQID { get; set; }
        public string RESPARTYID { get; set; }
        public Nullable<decimal> CUSTSEVERITY { get; set; }
        public Nullable<decimal> CUSTNEWSEVERITY { get; set; }
        public Nullable<decimal> ACCEPTRISK { get; set; }
        public Nullable<decimal> ACTUALCOMPLETIONDATE { get; set; }
        public string REQUIREMENTS { get; set; }
        public string ORIGINALSOD { get; set; }
        public string NEWSOD { get; set; }
        public Nullable<decimal> FMEAID { get; set; }
        public string MQVUSED { get; set; }
        public Nullable<decimal> CUSTOMERSEV { get; set; }
        public Nullable<decimal> MFGSEV { get; set; }
        public Nullable<decimal> DEFECTS { get; set; }
        public Nullable<decimal> POPULATION { get; set; }
        public Nullable<decimal> PPK { get; set; }
        public Nullable<decimal> DETECTIONGROUP { get; set; }
        public Nullable<decimal> LOCATIONGROUP { get; set; }
        public Nullable<decimal> METHODGROUP { get; set; }
        public Nullable<decimal> CONTROLSGROUP { get; set; }
        public Nullable<decimal> AUTOCTRLSGROUP { get; set; }
        public Nullable<decimal> NEWDEFECTS { get; set; }
        public Nullable<decimal> NEWPOPULATION { get; set; }
        public Nullable<decimal> NEWPPK { get; set; }
        public Nullable<decimal> NEWDETECTIONGROUP { get; set; }
        public Nullable<decimal> NEWLOCATIONGROUP { get; set; }
        public Nullable<decimal> NEWMETHODGROUP { get; set; }
        public Nullable<decimal> NEWCONTROLSGROUP { get; set; }
        public Nullable<decimal> NEWAUTOCTRLSGROUP { get; set; }
    }
}
