//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMFAILUREMODECODE
    {
        public decimal FAILUREID { get; set; }
        public string FAILURECODE { get; set; }
        public Nullable<decimal> FAILURENUMBER { get; set; }
        public string FAILDESC { get; set; }
    }
}
