//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMISITEM
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public decimal ISEQ { get; set; }
        public string IUSER1 { get; set; }
        public string IUSER2 { get; set; }
        public string IUSER3 { get; set; }
        public string IUSER4 { get; set; }
        public string IUSER5 { get; set; }
        public string IUSER6 { get; set; }
        public string IUSER7 { get; set; }
        public string IUSER8 { get; set; }
    }
}
