//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMISSHEET
    {
        public decimal ID { get; set; }
        public string DESCX { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string USER3 { get; set; }
        public string USER4 { get; set; }
        public string USER5 { get; set; }
        public string USER6 { get; set; }
        public string USER7 { get; set; }
        public string USER8 { get; set; }
        public Nullable<decimal> TOOLFLAG { get; set; }
        public string COL1 { get; set; }
        public string COL2 { get; set; }
        public string COL3 { get; set; }
        public string COL4 { get; set; }
        public string COL5 { get; set; }
        public string COL6 { get; set; }
        public string COL7 { get; set; }
        public string COL8 { get; set; }
        public Nullable<decimal> COLW1 { get; set; }
        public Nullable<decimal> COLW2 { get; set; }
        public Nullable<decimal> COLW3 { get; set; }
        public Nullable<decimal> COLW4 { get; set; }
        public Nullable<decimal> COLW5 { get; set; }
        public Nullable<decimal> COLW6 { get; set; }
        public Nullable<decimal> COLW7 { get; set; }
        public Nullable<decimal> COLW8 { get; set; }
        public Nullable<decimal> COL1TOOLDATA { get; set; }
        public Nullable<decimal> COL2TOOLDATA { get; set; }
        public Nullable<decimal> COL3TOOLDATA { get; set; }
        public Nullable<decimal> COL4TOOLDATA { get; set; }
        public Nullable<decimal> COL5TOOLDATA { get; set; }
        public Nullable<decimal> COL6TOOLDATA { get; set; }
        public Nullable<decimal> COL7TOOLDATA { get; set; }
        public Nullable<decimal> COL8TOOLDATA { get; set; }
        public Nullable<decimal> PLANTID { get; set; }
        public Nullable<decimal> PDMISSHEET1 { get; set; }
    }
}
