//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMISHDR
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public Nullable<decimal> SHEETTYPE { get; set; }
        public string DOCNAME { get; set; }
        public string ISUSER1 { get; set; }
        public string ISUSER2 { get; set; }
        public string ISUSER3 { get; set; }
        public string ISUSER4 { get; set; }
        public string ISUSER5 { get; set; }
        public string ISUSER6 { get; set; }
        public string ISUSER7 { get; set; }
        public string ISUSER8 { get; set; }
        public Nullable<decimal> TTKEY { get; set; }
        public Nullable<decimal> COMPLETETTKEY { get; set; }
        public Nullable<decimal> PRINTIMAGEFULLPAGE { get; set; }
    }
}
