//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMISGRAPHIC
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public decimal GSEQ { get; set; }
        public string CADFILENAME { get; set; }
        public Nullable<decimal> CADFILEKEY { get; set; }
        public Nullable<decimal> JPGFILEKEY { get; set; }
        public Nullable<decimal> CHECKOUTFLAG { get; set; }
        public string CHECKOUTENGINEER { get; set; }
    }
}
