//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMLPA_AUDITDOCHDR
    {
        public decimal AUDITID { get; set; }
        public Nullable<decimal> DOCID { get; set; }
        public Nullable<decimal> DOCSEQ { get; set; }
        public string DocDesc { get; set; }
        public Nullable<decimal> PLANTID { get; set; }
        public Nullable<decimal> GROUPID { get; set; }
        public string USERID { get; set; }
        public Nullable<decimal> SHIFT { get; set; }
        public string AuditYEAR { get; set; }
        public Nullable<decimal> WEEKREQUIRED { get; set; }
        public Nullable<decimal> DATEREQUIRED { get; set; }
        public Nullable<decimal> DATECOMPLETED { get; set; }
        public string TIMECOMPLETED { get; set; }
        public Nullable<decimal> AUDITSTATUS { get; set; }
        public string REASON { get; set; }
        public string DailyAudit { get; set; }
    }
}
