//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMLPALINE
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public decimal LINESEQ { get; set; }
        public decimal QID { get; set; }
    }
}
