//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMLPACORETEAM
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public decimal CORETEAMSEQ { get; set; }
        public string USERNAME { get; set; }
        public string USERID { get; set; }
        public string DEPARTMENT { get; set; }
        public string APPROVED { get; set; }
        public Nullable<decimal> APPROVALDATE { get; set; }
        public string APPROVALREQUIRED { get; set; }
    }
}
