//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMLPA_NUMBEROFWEEKS
    {
        public string AUDITYEAR { get; set; }
        public Nullable<decimal> MONTH1 { get; set; }
        public Nullable<decimal> MONTH2 { get; set; }
        public Nullable<decimal> MONTH3 { get; set; }
        public Nullable<decimal> MONTH4 { get; set; }
        public Nullable<decimal> MONTH5 { get; set; }
        public Nullable<decimal> MONTH6 { get; set; }
        public Nullable<decimal> MONTH7 { get; set; }
        public Nullable<decimal> MONTH8 { get; set; }
        public Nullable<decimal> MONTH9 { get; set; }
        public Nullable<decimal> MONTH10 { get; set; }
        public Nullable<decimal> MONTH11 { get; set; }
        public Nullable<decimal> MONTH12 { get; set; }
    }
}
