//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMLPAAUDITANSWER
    {
        public decimal AUDITID { get; set; }
        public Nullable<decimal> QID { get; set; }
        public Nullable<decimal> LINESEQ { get; set; }
        public Nullable<decimal> QPASS { get; set; }
        public string QINPUT { get; set; }
        public string QFAILREASONCODE { get; set; }
        public string QCOMMENT { get; set; }
        public string QMGRAPPROVALID { get; set; }
        public string QMGRCOMMENT { get; set; }
        public Nullable<decimal> QMGRAPPROVALDATE { get; set; }
        public Nullable<decimal> FailCategoryID { get; set; }
        public Nullable<decimal> AUDITORVERIFYDATE { get; set; }
        public string ALTMANAGERID { get; set; }
    }
}
