//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMLPA_EXCUSEDAUDITS
    {
        public decimal ExcusedAuditID { get; set; }
        public Nullable<decimal> PLANTID { get; set; }
        public Nullable<decimal> GROUPID { get; set; }
        public string USERID { get; set; }
        public Nullable<decimal> DOCID { get; set; }
        public Nullable<decimal> LocationLevel { get; set; }
        public string AUDITYEAR { get; set; }
        public Nullable<decimal> WEEKFROM { get; set; }
        public Nullable<decimal> WEEKTO { get; set; }
        public string REASON { get; set; }
    }
}
