//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMLPAHDR
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public string AUDITDESCRIPTION { get; set; }
        public string ZONE { get; set; }
        public string PARTNO { get; set; }
        public string CUSTOMER { get; set; }
        public Nullable<decimal> ORIGDATE { get; set; }
        public Nullable<decimal> REVDATE { get; set; }
        public string REVNUMBER { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public string PREPAREDBY { get; set; }
        public string APPROVALSTATUSFLAG { get; set; }
        public string ACTIONCOMMENT { get; set; }
        public string ALTMANAGERID { get; set; }
        public string ALTMANAGER { get; set; }
        public string AUDITORTOVERIFY { get; set; }
        public string PrintMsg { get; set; }
    }
}
