//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMMQVDEFECTMODE
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public decimal LINESEQ { get; set; }
        public decimal PROCESSSEQ { get; set; }
        public Nullable<decimal> FMEADATA { get; set; }
        public Nullable<decimal> BISDATA { get; set; }
        public Nullable<decimal> WARRANTYDATA { get; set; }
        public string COLORCODE { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public string USERDEF4 { get; set; }
        public string USERDEF5 { get; set; }
        public string USERDEF6 { get; set; }
        public string USERDEF7 { get; set; }
        public string USERDEF8 { get; set; }
        public string USERDEF9 { get; set; }
        public string USERDEF10 { get; set; }
        public Nullable<decimal> LEVELSEQ { get; set; }
    }
}
