//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMMQVMISC
    {
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public decimal LINESEQ { get; set; }
        public decimal PROCESSSEQ { get; set; }
        public Nullable<decimal> COMPSCORE { get; set; }
        public string COMMENTX { get; set; }
        public string ACTIONITEM { get; set; }
        public string RESPARTYID { get; set; }
        public string RESPARTY { get; set; }
        public Nullable<decimal> DUEDATE { get; set; }
        public string PCNNO { get; set; }
        public Nullable<decimal> LEVELSEQ { get; set; }
    }
}
