//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMPartMM
    {
        public decimal DocID { get; set; }
        public decimal DocSeq { get; set; }
        public string DocRecType { get; set; }
        public decimal DocType { get; set; }
        public string Filename { get; set; }
        public string FilepathX { get; set; }
        public decimal WPType { get; set; }
        public string DocDesc { get; set; }
        public decimal DocStatus { get; set; }
        public string Engineer { get; set; }
        public decimal Datex { get; set; }
        public string RevNumber { get; set; }
        public string SignOff { get; set; }
        public string Userdef1 { get; set; }
        public string Userdef2 { get; set; }
        public string Userdef3 { get; set; }
        public decimal TTKey { get; set; }
        public decimal CompleteTTKey { get; set; }
        public Nullable<decimal> CheckedOut { get; set; }
        public string CheckEngineer { get; set; }
        public Nullable<decimal> CheckDate { get; set; }
        public string PCNNO { get; set; }
        public string UserDef4 { get; set; }
        public Nullable<decimal> EffectiveDate { get; set; }
        public Nullable<decimal> EffectiveTo { get; set; }
        public Nullable<decimal> PendingFlag { get; set; }
        public string AltPCNNO { get; set; }
        public Nullable<decimal> DocGroupID { get; set; }
        public Nullable<decimal> PlantID { get; set; }
        public Nullable<decimal> TYPE { get; set; }
        public Nullable<decimal> InUseFlag { get; set; }
        public string InUseBy { get; set; }
        public Nullable<decimal> GERestricted { get; set; }
        public string GERestrictedReason { get; set; }
        public Nullable<decimal> GEExportStatus { get; set; }
        public string GEMasterDocID { get; set; }
        public string GEDocID { get; set; }
        public Nullable<decimal> GEStatus { get; set; }
        public Nullable<decimal> DocCategory { get; set; }
        public Nullable<decimal> FLMFREQUENCYID { get; set; }
    }
}
