//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMREMEDYPLANMULTISIGNOFF
    {
        public decimal DocID { get; set; }
        public decimal DocSeq { get; set; }
        public string DocRecType { get; set; }
        public decimal Seq { get; set; }
        public string ColumnHeader2 { get; set; }
        public string ColumnHeader3 { get; set; }
        public string ColumnHeader4 { get; set; }
        public string ColumnHeader5 { get; set; }
        public string ColumnHeader6 { get; set; }
        public string ColumnHeader7 { get; set; }
        public string ColumnInput2 { get; set; }
        public string ColumnInput3 { get; set; }
        public string ColumnInput4 { get; set; }
        public string ColumnInput5 { get; set; }
        public string ColumnInput6 { get; set; }
        public string ColumnInput7 { get; set; }
        public string InputHeader1 { get; set; }
        public string InputHeader2 { get; set; }
        public string InputHeader3 { get; set; }
        public string SignOffColumnHeader2 { get; set; }
        public string SignOffColumnHeader3 { get; set; }
        public string HasSerializedPartNo { get; set; }
        public string IsInspectorSignoff { get; set; }
        public string InspectorInputHeader1 { get; set; }
        public string InspectorInputHeader2 { get; set; }
        public string InspectorInputHeader3 { get; set; }
    }
}
