//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMRemedyPlanTabular
    {
        public decimal DocID { get; set; }
        public decimal DocSeq { get; set; }
        public string DocRecType { get; set; }
        public decimal Seq { get; set; }
        public decimal RowColSeq { get; set; }
        public string RowCol { get; set; }
        public string HeaderDesc { get; set; }
    }
}
