//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMRPItemValue
    {
        public decimal LineID { get; set; }
        public string EngineNo { get; set; }
        public string StationNo { get; set; }
        public decimal RecordSeq { get; set; }
        public decimal RemedyPlanSeq { get; set; }
        public string FailureDesc { get; set; }
        public string SupervisorAction { get; set; }
        public decimal PassFail { get; set; }
        public string UserInput { get; set; }
        public string Spare1 { get; set; }
        public string CommentX { get; set; }
        public string ReworkUserInput { get; set; }
        public string UserInputFailed { get; set; }
        public Nullable<decimal> UserInputfailed_operator_Clock { get; set; }
        public string UserInputfailed_USERID { get; set; }
        public Nullable<System.DateTime> UserInputfailed_Time_stamp { get; set; }
        public string UserInputfailed_Fail_flag { get; set; }
        public Nullable<decimal> UserInput_operator_Clock { get; set; }
        public string UserInput_UserID { get; set; }
        public Nullable<System.DateTime> UserInput_Time_stamp { get; set; }
        public string StopBuild { get; set; }
        public string Supervisor_UserID { get; set; }
        public string CheckMethod { get; set; }
        public Nullable<decimal> LowerValue { get; set; }
        public Nullable<decimal> UpperValue { get; set; }
        public Nullable<decimal> RecordType { get; set; }
        public Nullable<decimal> UserTTKey { get; set; }
        public string OperatorID { get; set; }
        public string UnitNo { get; set; }
        public string Severity { get; set; }
        public string InputRequired { get; set; }
        public Nullable<decimal> PlanType { get; set; }
        public Nullable<decimal> SHIFT { get; set; }
    }
}
