//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMRPDeviation
    {
        public string EngineNo { get; set; }
        public string StationNo { get; set; }
        public decimal RecordSeq { get; set; }
        public Nullable<System.DateTime> Datex { get; set; }
        public string OptionNo { get; set; }
        public string DeviationNo { get; set; }
        public Nullable<decimal> ResultFlag { get; set; }
        public string CommentX { get; set; }
        public string ReworkNotes1 { get; set; }
        public string ReworkNotes2 { get; set; }
        public string InspectionNotes { get; set; }
        public Nullable<decimal> ReworkClock1 { get; set; }
        public Nullable<decimal> ReworkClock2 { get; set; }
        public Nullable<decimal> InspectionClock { get; set; }
        public Nullable<decimal> Supervisor { get; set; }
        public string OperatorNotes { get; set; }
    }
}
