//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMREMEDYSMART
    {
        public decimal DOCID { get; set; }
        public decimal DOCSEQ { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public Nullable<decimal> DOCAID { get; set; }
        public Nullable<decimal> DOCBID { get; set; }
        public Nullable<decimal> DOCCID { get; set; }
        public decimal ROWCOLSEQ { get; set; }
        public string ROWCOL { get; set; }
        public string FORMULADESC { get; set; }
    }
}
