//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMRPITEMVALUESQCHOLDRELEASE
    {
        public string EngineNo { get; set; }
        public string StationNo { get; set; }
        public decimal RecordSeq { get; set; }
        public decimal RemedyPlanSeq { get; set; }
        public decimal MSeq { get; set; }
        public decimal QCHoldReleaseStatus { get; set; }
        public string QCHoldReleaseID { get; set; }
        public System.DateTime QCHoldReleaseDate { get; set; }
        public string QCHoldReleaseComment { get; set; }
        public decimal FailureIndex { get; set; }
    }
}
