//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMRPData
    {
        public Nullable<decimal> LineID { get; set; }
        public string EngineNo { get; set; }
        public string StationNo { get; set; }
        public decimal RecordSeq { get; set; }
        public Nullable<System.DateTime> Datex { get; set; }
        public string OptionNo { get; set; }
        public string OPNO { get; set; }
        public string Subheader { get; set; }
        public string RemedyPlanDesc { get; set; }
        public Nullable<decimal> ResultFlag { get; set; }
        public Nullable<decimal> OperatorX { get; set; }
        public Nullable<decimal> Supervisor { get; set; }
        public Nullable<decimal> DocID { get; set; }
        public string DocRecType { get; set; }
        public Nullable<decimal> DocSeq { get; set; }
        public Nullable<decimal> PlanType { get; set; }
        public string OperatorNotes { get; set; }
        public string SupervisorNotes { get; set; }
        public string ReworkNotes { get; set; }
        public Nullable<decimal> ReworkClockNo { get; set; }
        public Nullable<System.DateTime> ReworkDateX { get; set; }
        public string ReworkInsNotes { get; set; }
        public Nullable<decimal> ReworkInsClockNo { get; set; }
        public Nullable<System.DateTime> ReworkInsDateX { get; set; }
        public string AuditorNotes { get; set; }
        public Nullable<decimal> AuditorClockNo { get; set; }
        public Nullable<decimal> TTKey { get; set; }
        public string StopBuild { get; set; }
        public Nullable<decimal> RecordType { get; set; }
        public string SignoffUser1 { get; set; }
        public string SignoffUser2 { get; set; }
        public Nullable<decimal> SHID { get; set; }
        public Nullable<decimal> SHIFT { get; set; }
        public Nullable<decimal> FREQUENCYTYPE { get; set; }
    }
}
