//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMSEVCODE
    {
        public decimal SEVNUMBER { get; set; }
        public string SEVDESC { get; set; }
        public string SEVCOMMENT { get; set; }
        public string CUST_DESC { get; set; }
        public string CUST_EFFECT { get; set; }
    }
}
