//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMTT2CONFIG
    {
        public decimal TOOLTYPE2 { get; set; }
        public decimal TOOLTYPE1 { get; set; }
        public string TYPEDESC { get; set; }
        public string TYPEDESC2 { get; set; }
    }
}
