//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMTOOLLIST
    {
        public string TOOLNUMBER { get; set; }
        public decimal TOOLTYPE1 { get; set; }
        public string DESCX { get; set; }
        public decimal TOOLTYPE2 { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string USER3 { get; set; }
        public string USER4 { get; set; }
        public Nullable<decimal> TOOLINDEX1 { get; set; }
        public Nullable<decimal> TOOLINDEX2 { get; set; }
        public Nullable<decimal> TOOLINDEX3 { get; set; }
        public Nullable<decimal> TOOLINDEX4 { get; set; }
        public string DESCX2 { get; set; }
    }
}
