//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMTOOLINDEX2
    {
        public decimal TOOLINDEX2 { get; set; }
        public string INDEX2DESC { get; set; }
        public decimal TOOLINDEX1 { get; set; }
    }
}
