//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMTTCONFIG
    {
        public decimal ID { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string USER3 { get; set; }
        public string USER4 { get; set; }
        public string AUTOMATETOOL { get; set; }
        public Nullable<decimal> NEXTTOOLNUM { get; set; }
    }
}
