//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMWorkGroup
    {
        public string WorkGroupID { get; set; }
        public string WGDescription { get; set; }
        public Nullable<short> PlantID { get; set; }
        public Nullable<int> SafetyRating { get; set; }
        public Nullable<int> ErgoRating { get; set; }
        public Nullable<int> TPMRating { get; set; }
        public Nullable<short> Net { get; set; }
        public Nullable<short> WgStatus { get; set; }
        public string CheckEngineer { get; set; }
    }
}
