//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMWorkStation
    {
        public int WSID { get; set; }
        public string WSCode { get; set; }
        public string WSDesc { get; set; }
        public string WC { get; set; }
        public Nullable<short> Net { get; set; }
        public Nullable<short> FiveSRating { get; set; }
        public Nullable<double> CostRate1 { get; set; }
        public Nullable<double> CostRate2 { get; set; }
        public Nullable<int> MachineEff { get; set; }
        public Nullable<short> SkillLevel { get; set; }
        public Nullable<short> NumMen { get; set; }
        public string CheckEngineer { get; set; }
        public decimal PlantID { get; set; }
        public string MachineType { get; set; }
        public string RFCEngineer { get; set; }
    }
}
