//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMWorkCenterText
    {
        public string WC { get; set; }
        public short EnggFunction { get; set; }
        public decimal TTKey { get; set; }
        public Nullable<short> WP { get; set; }
        public byte[] Text { get; set; }
        public decimal PlantID { get; set; }
    }
}
