//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDMWorkCenterMM1
    {
        public string WC { get; set; }
        public short MSeq { get; set; }
        public short EnggFunction { get; set; }
        public short InfoType { get; set; }
        public string Filename { get; set; }
        public Nullable<short> WPType { get; set; }
        public Nullable<short> PrintOrder { get; set; }
        public string FilepathX { get; set; }
        public Nullable<decimal> TTKey { get; set; }
        public string DocDesc { get; set; }
        public Nullable<short> DocStatus { get; set; }
        public string Engineer { get; set; }
        public Nullable<decimal> Datex { get; set; }
        public string RevNumber { get; set; }
        public Nullable<short> CheckedOut { get; set; }
        public string CheckEngineer { get; set; }
        public Nullable<decimal> CheckDate { get; set; }
        public string SignOff { get; set; }
        public decimal CompleteTTKey { get; set; }
        public decimal DocID { get; set; }
        public decimal DocSeq { get; set; }
        public string DocRecType { get; set; }
        public Nullable<short> RequiredDoc { get; set; }
        public string Userdef1 { get; set; }
        public string Userdef2 { get; set; }
        public string Userdef3 { get; set; }
        public string UserDef4 { get; set; }
        public Nullable<decimal> EffectiveDate { get; set; }
        public Nullable<decimal> EffectiveTo { get; set; }
        public string PCNNO { get; set; }
        public decimal PlantID { get; set; }
        public Nullable<decimal> MDMDocID { get; set; }
        public Nullable<decimal> MDMDocSeq { get; set; }
        public Nullable<decimal> InUseFlag { get; set; }
        public string InUseBy { get; set; }
        public string ALTPCNNO { get; set; }
        public Nullable<decimal> GERestricted { get; set; }
        public string GERestrictedReason { get; set; }
        public Nullable<decimal> GEExportStatus { get; set; }
        public string GEMasterDocID { get; set; }
        public string GEDocID { get; set; }
        public Nullable<decimal> GEStatus { get; set; }
        public Nullable<decimal> PENDINGFLAG { get; set; }
        public Nullable<decimal> DocCategory { get; set; }
    }
}
