//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTMODELDESTINATION
    {
        public decimal PLANTMODELID { get; set; }
        public decimal DESTINATIONID { get; set; }
        public string DESTINATIONNAME { get; set; }
        public decimal DESTINATIONSEQ { get; set; }
    }
}
