//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROUTEHDR
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public Nullable<decimal> LOTSIZE { get; set; }
        public string AUTHREL { get; set; }
        public string ENG { get; set; }
        public Nullable<decimal> RELDATE { get; set; }
        public string USER0 { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string USER3 { get; set; }
        public Nullable<decimal> MATCOST { get; set; }
        public Nullable<decimal> EXPUNIT { get; set; }
        public Nullable<decimal> EXPLOT { get; set; }
        public Nullable<decimal> CCOST { get; set; }
        public Nullable<decimal> SCOST { get; set; }
        public string CHANGE { get; set; }
        public Nullable<decimal> TCOST { get; set; }
        public Nullable<decimal> TOOLCOSTS { get; set; }
        public Nullable<decimal> NOP { get; set; }
        public string PARTDESC { get; set; }
        public Nullable<decimal> NET { get; set; }
        public string USERID { get; set; }
        public Nullable<decimal> SETUPHRS { get; set; }
        public Nullable<decimal> RUNHRS { get; set; }
        public Nullable<decimal> FLAG1 { get; set; }
        public Nullable<decimal> FLAG2 { get; set; }
        public Nullable<decimal> FLAG3 { get; set; }
        public string MASTERPART { get; set; }
        public Nullable<decimal> TAKTTIME { get; set; }
        public Nullable<decimal> NetDate { get; set; }
        public Nullable<decimal> PLANTID { get; set; }
        public Nullable<decimal> PARTREV { get; set; }
        public Nullable<decimal> LOCKPLAN { get; set; }
        public Nullable<decimal> ContinousFlow { get; set; }
        public Nullable<decimal> SHLevel { get; set; }
    }
}
