//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHELEFORM
    {
        public decimal SHID { get; set; }
        public decimal ELEID { get; set; }
        public Nullable<decimal> FORMULA1 { get; set; }
        public Nullable<decimal> FORMULA2 { get; set; }
        public Nullable<decimal> FORMULA3 { get; set; }
        public Nullable<decimal> FORMULA4 { get; set; }
        public Nullable<decimal> FORMULA5 { get; set; }
        public Nullable<decimal> FORMULA6 { get; set; }
        public Nullable<decimal> FORMULA7 { get; set; }
        public Nullable<decimal> FORMULA8 { get; set; }
        public Nullable<decimal> FORMULA9 { get; set; }
        public Nullable<decimal> FORMULA10 { get; set; }
    }
}
