//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHMATERIAL
    {
        public decimal SHID { get; set; }
        public decimal MSEQ { get; set; }
        public string DESCX { get; set; }
        public string UM { get; set; }
        public Nullable<decimal> MATLTYPE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<decimal> FREQ { get; set; }
        public Nullable<decimal> TOTALCOST { get; set; }
        public Nullable<decimal> ELETYPE { get; set; }
        public Nullable<decimal> SPARE { get; set; }
        public Nullable<decimal> ELEID { get; set; }
        public string MATNUMBER { get; set; }
        public string ASF { get; set; }
        public string LOCATIONS { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string DestinationFlag { get; set; }
        public Nullable<decimal> WPType { get; set; }
        public Nullable<decimal> TTKey { get; set; }
        public Nullable<decimal> MDMDocID { get; set; }
        public Nullable<decimal> MDMDocSeq { get; set; }
        public string USER3 { get; set; }
    }
}
