//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHMM
    {
        public decimal SHID { get; set; }
        public decimal MSEQ { get; set; }
        public decimal TYPE { get; set; }
        public string FILENAME { get; set; }
        public Nullable<decimal> WPTYPE { get; set; }
        public Nullable<decimal> PRINTORDER { get; set; }
        public string FILEPATHX { get; set; }
        public Nullable<decimal> ttkey { get; set; }
        public string DocDesc { get; set; }
        public Nullable<decimal> Doctype { get; set; }
        public Nullable<decimal> MDMDocID { get; set; }
        public Nullable<decimal> MDMDocSeq { get; set; }
        public Nullable<decimal> CompleteTTKey { get; set; }
        public Nullable<decimal> DocCategory { get; set; }
    }
}
