//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHTOOL
    {
        public decimal SHID { get; set; }
        public decimal TSEQ { get; set; }
        public string TDESC { get; set; }
        public Nullable<decimal> TCOST { get; set; }
        public Nullable<decimal> TQTY { get; set; }
        public string TTYPE { get; set; }
        public string TOOLNUM { get; set; }
        public string TOOLFLAG { get; set; }
        public string LOCATION { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<decimal> SPARE { get; set; }
        public string CELL { get; set; }
        public Nullable<decimal> WPType { get; set; }
        public Nullable<decimal> TTKey { get; set; }
        public Nullable<decimal> MDMDocID { get; set; }
        public Nullable<decimal> MDMDocSeq { get; set; }
        public string USER1 { get; set; }
        public string USER2 { get; set; }
        public string USER3 { get; set; }
    }
}
