//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMFunctionCourse
    {
        public decimal FunctionID { get; set; }
        public decimal CourseID { get; set; }
        public decimal CourseSeq { get; set; }
        public string CourseDescX { get; set; }
        public Nullable<decimal> ActiveFlag { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
    }
}
