//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMOperatorSkill
    {
        public string USERID { get; set; }
        public decimal FunctionID { get; set; }
        public decimal CourseID { get; set; }
        public decimal RecordSeq { get; set; }
        public Nullable<decimal> DateComplete { get; set; }
        public Nullable<decimal> StatusX { get; set; }
        public Nullable<decimal> LastUpdatedDate { get; set; }
        public string Resultx { get; set; }
        public Nullable<decimal> InputType { get; set; }
    }
}
