//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMOperatorCheckListAnswer
    {
        public string USERID { get; set; }
        public decimal SEQX { get; set; }
        public decimal DOCID { get; set; }
        public string DOCRECTYPE { get; set; }
        public decimal DOCSEQ { get; set; }
        public decimal WSID { get; set; }
        public decimal QRecordSeq { get; set; }
        public Nullable<decimal> DateComplete { get; set; }
        public Nullable<decimal> ResultData { get; set; }
        public string CommentX { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
    }
}
