//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMQuestion
    {
        public decimal QID { get; set; }
        public string AUDITDESC { get; set; }
        public string QUESTIONTEXT { get; set; }
        public Nullable<decimal> INPUTYN { get; set; }
        public string STATIONS { get; set; }
        public Nullable<decimal> GENERIC { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> TTKey { get; set; }
        public string FileNameX { get; set; }
        public Nullable<decimal> WP { get; set; }
    }
}
