//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBHDR
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public string OPNO { get; set; }
        public decimal SHID { get; set; }
        public decimal SHSEQ { get; set; }
        public string DESCX { get; set; }
        public string CHANGEFLAG { get; set; }
        public Nullable<decimal> MODEL1 { get; set; }
        public Nullable<decimal> MODEL2 { get; set; }
        public Nullable<decimal> DESTINATION1 { get; set; }
        public Nullable<decimal> DESTINATION2 { get; set; }
        public Nullable<decimal> OPTION1 { get; set; }
        public Nullable<decimal> OPTION2 { get; set; }
        public Nullable<decimal> EXCLUDEFROMPRINT { get; set; }
        public Nullable<decimal> SETUPTIME { get; set; }
        public Nullable<decimal> CYCLETIME { get; set; }
        public Nullable<decimal> GANTTSTARTFROM { get; set; }
        public Nullable<decimal> LBSTICKY { get; set; }
        public string MISCFLAG1 { get; set; }
        public string MISCFLAG2 { get; set; }
        public string MISCFLAG3 { get; set; }
        public string MISCFLAG4 { get; set; }
        public Nullable<decimal> SHType { get; set; }
        public Nullable<decimal> LaborType { get; set; }
        public string NumMen { get; set; }
        public string DESC2 { get; set; }
        public string PLATTENID { get; set; }
    }
}
