//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_OPHEADER
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public string OPNO { get; set; }
        public string TEAM { get; set; }
        public string PRODUCTX { get; set; }
        public string PREPAREDBY { get; set; }
        public decimal TEMPLATEID { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATHX { get; set; }
        public Nullable<decimal> TTKEY { get; set; }
        public Nullable<decimal> OPEREFFICIENCY { get; set; }
        public string STDWIP { get; set; }
        public Nullable<decimal> WAITINGTIME { get; set; }
        public string NOTESSAFETY { get; set; }
        public string IEOPS { get; set; }
    }
}
