//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_Signoff
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public string OPNO { get; set; }
        public decimal RECSEQ { get; set; }
        public decimal Shift { get; set; }
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public decimal PLANTID { get; set; }
        public Nullable<decimal> GROUPID { get; set; }
        public Nullable<decimal> StatusX { get; set; }
        public Nullable<decimal> EmailDate { get; set; }
        public Nullable<decimal> SignoffDate { get; set; }
        public string MISC1 { get; set; }
        public string MISC2 { get; set; }
        public string MISC3 { get; set; }
    }
}
