//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_SUBHEADER
    {
        public decimal SHID { get; set; }
        public string CHECKX { get; set; }
        public string TOOLNUM1 { get; set; }
        public string TOOLNUM2 { get; set; }
        public string TOOLNUM3 { get; set; }
        public Nullable<decimal> OBTIME { get; set; }
        public Nullable<decimal> KEYPOINT1 { get; set; }
        public Nullable<decimal> KEYPOINT2 { get; set; }
        public Nullable<decimal> KEYPOINT3 { get; set; }
        public string KEYPOINTTEXT1 { get; set; }
        public string KEYPOINTTEXT2 { get; set; }
        public string KEYPOINTTEXT3 { get; set; }
        public string FILENAME { get; set; }
        public string FILEPATHX { get; set; }
        public Nullable<decimal> TTKEY { get; set; }
        public Nullable<decimal> VATIME { get; set; }
        public Nullable<decimal> NVATIME { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> MANUALTIME { get; set; }
        public Nullable<decimal> PROCESSTIME { get; set; }
        public Nullable<decimal> WALKTIME { get; set; }
    }
}
