//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTRUC
    {
        public string BUCODE { get; set; }
        public decimal CELLTYPE { get; set; }
        public decimal SEQ { get; set; }
        public string DESCX { get; set; }
    }
}
