//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLTYPE2
    {
        public decimal TOOLType2ID { get; set; }
        public string TOOLTYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> TOOLType1ID { get; set; }
        public Nullable<short> ACTIVEFLAG { get; set; }
    }
}
