//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLITEM
    {
        public string ITEMNUM { get; set; }
        public string ITEMDESC { get; set; }
        public Nullable<decimal> ITEMTYPE { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public Nullable<decimal> PERISHABLEFLAG { get; set; }
        public Nullable<decimal> PURGEFLAG { get; set; }
        public string OEMNUMBER { get; set; }
        public Nullable<decimal> ITEMCOST { get; set; }
        public string ITEMMATL { get; set; }
    }
}
