//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLTYPE1
    {
        public decimal TOOLType1ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string TOOLITEMFLAG { get; set; }
        public string TOOLCALIBFLAG { get; set; }
        public string AUTOMATETOOL { get; set; }
        public Nullable<decimal> NEXTTOOLNUM { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public string USERDEF4 { get; set; }
        public string USERDEF5 { get; set; }
        public Nullable<short> ACTIVEFLAG { get; set; }
        public string TOOLENGINEEREMAIL { get; set; }
        public string ESCALATIONEMAIL { get; set; }
    }
}
