//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLITEMGRAPHIC
    {
        public string ITEMNUM { get; set; }
        public string FPATH { get; set; }
        public string FNAME { get; set; }
        public string FDATETIME { get; set; }
        public decimal DSEQ { get; set; }
        public string DOCDESC { get; set; }
        public Nullable<decimal> DOCTYPE { get; set; }
        public Nullable<decimal> WPTYPE { get; set; }
        public Nullable<decimal> MDMDocID { get; set; }
        public Nullable<decimal> MDMDocSEQ { get; set; }
        public Nullable<decimal> TTKEY { get; set; }
        public Nullable<decimal> COMPLETETTKEY { get; set; }
    }
}
