//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolType5
    {
        public decimal ToolTypeID5 { get; set; }
        public string Index5DESC { get; set; }
        public decimal ToolTypeID4 { get; set; }
    }
}
