//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLTEXT
    {
        public decimal TOOLTYPE1ID { get; set; }
        public decimal TOOLTYPE2ID { get; set; }
        public string TOOLNUM { get; set; }
        public string TOOLRECTYPE { get; set; }
        public decimal TOOLSEQ { get; set; }
        public byte[] TEXT { get; set; }
        public decimal TTKEY { get; set; }
        public Nullable<decimal> WP { get; set; }
    }
}
