//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolType3
    {
        public decimal ToolTypeID3 { get; set; }
        public string Index3DESC { get; set; }
        public decimal ToolTypeID2 { get; set; }
    }
}
