//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLHEADER
    {
        public decimal TOOLTYPE1ID { get; set; }
        public decimal TOOLTYPE2ID { get; set; }
        public string TOOLNUM { get; set; }
        public string TOOLRECTYPE { get; set; }
        public decimal TOOLSEQ { get; set; }
        public string DESCRIPTION { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USERDEF3 { get; set; }
        public string USERDEF4 { get; set; }
        public string USERDEF5 { get; set; }
        public string ENGINEER { get; set; }
        public Nullable<decimal> RELEASEDFLAG { get; set; }
        public Nullable<decimal> RELEASEDATE { get; set; }
        public string REVNUMBER { get; set; }
        public Nullable<decimal> CHECKEDOUT { get; set; }
        public string CHECKENGINEER { get; set; }
        public Nullable<decimal> CHECKDATE { get; set; }
        public Nullable<decimal> TOOLCOST { get; set; }
        public string OLDTOOL { get; set; }
        public Nullable<decimal> ACTIVEFLAG { get; set; }
        public string STATUSCOMMENT { get; set; }
        public Nullable<decimal> MULTIUSEFLAG { get; set; }
        public Nullable<decimal> USAGETYPE { get; set; }
        public Nullable<decimal> ALTERNATETOOL { get; set; }
        public string SPARESLOCATION { get; set; }
        public Nullable<decimal> NEXTUNIQUETOOLNUM { get; set; }
        public Nullable<decimal> CALIBRATIONTYPE { get; set; }
        public string SUPPLIERCODE { get; set; }
        public string SUPPLIERNAME { get; set; }
        public Nullable<decimal> CALIBRATIONCOST { get; set; }
        public Nullable<decimal> MAXIMOLINK { get; set; }
        public string ITEMSETID { get; set; }
        public string CUMMINS_SITE { get; set; }
        public string STOREROOM { get; set; }
        public Nullable<decimal> TOOLTYPEID3 { get; set; }
        public Nullable<decimal> TOOLTYPEID4 { get; set; }
        public Nullable<decimal> TOOLTYPEID5 { get; set; }
        public string DESCX2 { get; set; }
        public string MaximoDrawing { get; set; }
        public Nullable<decimal> MaximoSTF { get; set; }
    }
}
