//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLMM
    {
        public decimal TOOLTYPE1ID { get; set; }
        public decimal TOOLTYPE2ID { get; set; }
        public string TOOLNUM { get; set; }
        public string TOOLRECTYPE { get; set; }
        public decimal TOOLSEQ { get; set; }
        public decimal DOCSEQ { get; set; }
        public string DOCDESC { get; set; }
        public decimal TYPEX { get; set; }
        public Nullable<decimal> DOCTYPE { get; set; }
        public Nullable<decimal> WPTYPE { get; set; }
        public Nullable<decimal> MDMDocID { get; set; }
        public Nullable<decimal> MDMDocSEQ { get; set; }
        public string FILEPATHX { get; set; }
        public string FILENAMEX { get; set; }
        public string FILEDATETIME { get; set; }
        public Nullable<decimal> TTKEY { get; set; }
        public Nullable<decimal> COMPLETETTKEY { get; set; }
        public string CHECKENGINEER { get; set; }
        public Nullable<decimal> CHECKDATE { get; set; }
        public Nullable<decimal> CHECKEDOUT { get; set; }
    }
}
