//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLMaximoItemMaster
    {
        public string TOOLNUM { get; set; }
        public string ToolDescription { get; set; }
        public string Manufacturer { get; set; }
        public string OEM { get; set; }
        public string PlantCode { get; set; }
        public Nullable<decimal> ACTIVEFLAG { get; set; }
        public Nullable<decimal> ToolOwner { get; set; }
    }
}
