//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WITEXT
    {
        public decimal ID { get; set; }
        public string RECTYPE { get; set; }
        public decimal SEQ { get; set; }
        public string OPNO { get; set; }
        public Nullable<decimal> WP { get; set; }
        public byte[] TEXT { get; set; }
        public decimal ttkey { get; set; }
    }
}
