//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Explore1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKCEN
    {
        public string WC { get; set; }
        public string DESCX { get; set; }
        public Nullable<decimal> COSTREC { get; set; }
        public Nullable<decimal> CYCLEPFD { get; set; }
        public Nullable<decimal> SETUPPFD { get; set; }
        public Nullable<decimal> CYCLEREAL { get; set; }
        public Nullable<decimal> SETUPREAL { get; set; }
        public Nullable<decimal> NET { get; set; }
        public decimal PLANTID { get; set; }
    }
}
